export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';

export const RESET_USER = 'RESET_USER';

export const SET_USER = 'SET_USER';