export const ADD_INVESTMENT_REQUEST = 'ADD_INVESTMENT_REQUEST';
export const ADD_INVESTMENT_FAILURE = 'ADD_INVESTMENT_FAILURE';
export const ADD_INVESTMENT_SUCCESS = 'ADD_INVESTMENT_SUCCESS';

export const UPDATE_INVESTMENT_REQUEST = 'UPDATE_INVESTMENT_REQUEST';
export const UPDATE_INVESTMENT_FAILURE = 'UPDATE_INVESTMENT_FAILURE';
export const UPDATE_INVESTMENT_SUCCESS = 'UPDATE_INVESTMENT_SUCCESS';

export const REMOVE_INVESTMENT_REQUEST = 'REMOVE_INVESTMENT_REQUEST';
export const REMOVE_INVESTMENT_FAILURE = 'REMOVE_INVESTMENT_FAILURE';
export const REMOVE_INVESTMENT_SUCCESS = 'REMOVE_INVESTMENT_SUCCESS';

export const LOAD_INVESTMENT_REQUEST = 'LOAD_INVESTMENT_REQUEST';
export const LOAD_INVESTMENT_FAILURE = 'LOAD_INVESTMENT_FAILURE';
export const LOAD_INVESTMENT_SUCCESS = 'LOAD_INVESTMENT_SUCCESS';