export const ADD_PORTFOLIO_REQUEST = 'ADD_PORTFOLIO_REQUEST';
export const ADD_PORTFOLIO_FAILURE = 'ADD_PORTFOLIO_FAILURE';
export const ADD_PORTFOLIO_SUCCESS = 'ADD_PORTFOLIO_SUCCESS';

export const UPDATE_PORTFOLIO_REQUEST = 'UPDATE_PORTFOLIO_REQUEST';
export const UPDATE_PORTFOLIO_FAILURE = 'UPDATE_PORTFOLIO_FAILURE';
export const UPDATE_PORTFOLIO_SUCCESS = 'UPDATE_PORTFOLIO_SUCCESS';

export const REMOVE_PORTFOLIO_REQUEST = 'REMOVE_PORTFOLIO_REQUEST';
export const REMOVE_PORTFOLIO_FAILURE = 'REMOVE_PORTFOLIO_FAILURE';
export const REMOVE_PORTFOLIO_SUCCESS = 'REMOVE_PORTFOLIO_SUCCESS';

export const LOAD_PORTFOLIOS_REQUEST = 'LOAD_PORTFOLIOS_REQUEST';
export const LOAD_PORTFOLIOS_FAILURE = 'LOAD_PORTFOLIOS_FAILURE';
export const LOAD_PORTFOLIOS_SUCCESS = 'LOAD_PORTFOLIOS_SUCCESS';

export const ADD_PORTFOLIO_INVESTMENT = 'ADD_PORTFOLIO_INVESTMENT';